"""
J1939 Fleet Matrix: 10 Major Commercial / Automotive Brands x 3 Iconic Models = 30 Vehicles
Each vehicle contains unique SAE J1939 Source Address (SA), specs, and telemetry status.
"""

from typing import Dict, List, Any


FLEET_BRANDS = [
    {
        "id": "mercedes",
        "name": "Mercedes-Benz",
        "country": "Germany",
        "color": "#00D2FF",
        "badge": "MB",
        "accent": "rgba(0, 210, 255, 0.2)",
    },
    {
        "id": "scania",
        "name": "Scania",
        "country": "Sweden",
        "color": "#FF4B4B",
        "badge": "SC",
        "accent": "rgba(255, 75, 75, 0.2)",
    },
    {
        "id": "volvo",
        "name": "Volvo Trucks",
        "country": "Sweden",
        "color": "#00FF9D",
        "badge": "VL",
        "accent": "rgba(0, 255, 157, 0.2)",
    },
    {
        "id": "man",
        "name": "MAN Truck & Bus",
        "country": "Germany",
        "color": "#FFA500",
        "badge": "MN",
        "accent": "rgba(255, 165, 0, 0.2)",
    },
    {
        "id": "daf",
        "name": "DAF Trucks",
        "country": "Netherlands",
        "color": "#E6C200",
        "badge": "DF",
        "accent": "rgba(230, 194, 0, 0.2)",
    },
    {
        "id": "iveco",
        "name": "Iveco",
        "country": "Italy",
        "color": "#38EF7D",
        "badge": "IV",
        "accent": "rgba(56, 239, 125, 0.2)",
    },
    {
        "id": "ford_trucks",
        "name": "Ford Trucks",
        "country": "Turkey / Global",
        "color": "#118AB2",
        "badge": "FT",
        "accent": "rgba(17, 138, 178, 0.2)",
    },
    {
        "id": "renault_trucks",
        "name": "Renault Trucks",
        "country": "France",
        "color": "#FF0055",
        "badge": "RN",
        "accent": "rgba(255, 0, 85, 0.2)",
    },
    {
        "id": "isuzu",
        "name": "Isuzu",
        "country": "Japan",
        "color": "#9D4EDD",
        "badge": "IS",
        "accent": "rgba(157, 78, 221, 0.2)",
    },
    {
        "id": "bmc",
        "name": "BMC Otomotiv",
        "country": "Turkey",
        "color": "#06D6A0",
        "badge": "BM",
        "accent": "rgba(6, 214, 160, 0.2)",
    },
]


VEHICLES: List[Dict[str, Any]] = [
    # 1. Mercedes-Benz (SA: 0x01, 0x02, 0x03)
    {
        "id": "mb-actros-1851",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "Actros 1851 GigaSpace",
        "category": "Uzun Yol Çekici",
        "plate": "34 MB 1851",
        "source_address": 0x01,  # J1939 SA: 1
        "engine": "OM471 12.8L 510 HP",
        "max_speed": 130.0,
        "default_speed": 85.0,
        "current_speed": 85.0,
        "target_speed": 85.0,
        "acceleration_rate": 2.5,  # km/h per second
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "mb-arocs-3353",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "Arocs 3353 6x4",
        "category": "Ağır Şantiye / Damper",
        "plate": "34 MB 3353",
        "source_address": 0x02,  # J1939 SA: 2
        "engine": "OM473 15.6L 530 HP",
        "max_speed": 110.0,
        "default_speed": 45.0,
        "current_speed": 45.0,
        "target_speed": 45.0,
        "acceleration_rate": 2.0,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },
    {
        "id": "mb-atego-1518",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "Atego 1518 Distribution",
        "category": "Şehir İçi Dağıtım Kamyonu",
        "plate": "34 MB 1518",
        "source_address": 0x03,  # J1939 SA: 3
        "engine": "OM934 5.1L 177 HP",
        "max_speed": 120.0,
        "default_speed": 60.0,
        "current_speed": 60.0,
        "target_speed": 60.0,
        "acceleration_rate": 3.0,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 2. Scania (SA: 0x04, 0x05, 0x06)
    {
        "id": "scania-770s-v8",
        "brand_id": "scania",
        "brand_name": "Scania",
        "model": "770 S V8 Highline",
        "category": "King of the Road Çekici",
        "plate": "34 SC 770",
        "source_address": 0x04,  # J1939 SA: 4
        "engine": "DC16 16.4L V8 770 HP",
        "max_speed": 140.0,
        "default_speed": 90.0,
        "current_speed": 90.0,
        "target_speed": 90.0,
        "acceleration_rate": 3.2,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "scania-r500-super",
        "brand_id": "scania",
        "brand_name": "Scania",
        "model": "R 500 Super 4x2",
        "category": "Filo Uzun Yol Çekici",
        "plate": "34 SC 500",
        "source_address": 0x05,  # J1939 SA: 5
        "engine": "DC13 Super 13.0L 500 HP",
        "max_speed": 130.0,
        "default_speed": 82.0,
        "current_speed": 82.0,
        "target_speed": 82.0,
        "acceleration_rate": 2.6,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "scania-g410-xt",
        "brand_id": "scania",
        "brand_name": "Scania",
        "model": "G 410 XT Construction",
        "category": "XT Ağır İnşaat Kamyonu",
        "plate": "34 SC 410",
        "source_address": 0x06,  # J1939 SA: 6
        "engine": "DC13 12.7L 410 HP",
        "max_speed": 115.0,
        "default_speed": 50.0,
        "current_speed": 50.0,
        "target_speed": 50.0,
        "acceleration_rate": 2.2,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 3. Volvo Trucks (SA: 0x07, 0x08, 0x09)
    {
        "id": "volvo-fh16-750",
        "brand_id": "volvo",
        "brand_name": "Volvo Trucks",
        "model": "FH16 750 Globetrotter XXL",
        "category": "Ağır Yük & Uzun Yol Çekici",
        "plate": "34 VL 750",
        "source_address": 0x07,  # J1939 SA: 7
        "engine": "D16K 16.1L 750 HP",
        "max_speed": 140.0,
        "default_speed": 88.0,
        "current_speed": 88.0,
        "target_speed": 88.0,
        "acceleration_rate": 3.0,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "volvo-fm-460",
        "brand_id": "volvo",
        "brand_name": "Volvo Trucks",
        "model": "FM 460 Globetrotter",
        "category": "Bölgesel Lojistik & Tanker",
        "plate": "34 VL 460",
        "source_address": 0x08,  # J1939 SA: 8
        "engine": "D13K 12.8L 460 HP",
        "max_speed": 125.0,
        "default_speed": 75.0,
        "current_speed": 75.0,
        "target_speed": 75.0,
        "acceleration_rate": 2.5,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "volvo-fmx-500",
        "brand_id": "volvo",
        "brand_name": "Volvo Trucks",
        "model": "FMX 500 8x4 Heavy Duty",
        "category": "Maden & Şantiye Damperli",
        "plate": "34 VL 500",
        "source_address": 0x09,  # J1939 SA: 9
        "engine": "D13K 12.8L 500 HP",
        "max_speed": 105.0,
        "default_speed": 40.0,
        "current_speed": 40.0,
        "target_speed": 40.0,
        "acceleration_rate": 1.9,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 4. MAN Truck & Bus (SA: 0x0A, 0x0B, 0x0C)
    {
        "id": "man-tgx-18640",
        "brand_id": "man",
        "brand_name": "MAN Truck & Bus",
        "model": "TGX 18.640 Individual Lion S",
        "category": "Premium Uzun Yol Çekici",
        "plate": "34 MN 640",
        "source_address": 0x0A,  # J1939 SA: 10
        "engine": "D3876 15.2L 640 HP",
        "max_speed": 135.0,
        "default_speed": 89.0,
        "current_speed": 89.0,
        "target_speed": 89.0,
        "acceleration_rate": 2.8,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "man-tgs-33510",
        "brand_id": "man",
        "brand_name": "MAN Truck & Bus",
        "model": "TGS 33.510 6x6 HydroDrive",
        "category": "Şantiye & Zorlu Arazi Kamyonu",
        "plate": "34 MN 510",
        "source_address": 0x0B,  # J1939 SA: 11
        "engine": "D2676 12.4L 510 HP",
        "max_speed": 110.0,
        "default_speed": 55.0,
        "current_speed": 55.0,
        "target_speed": 55.0,
        "acceleration_rate": 2.1,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },
    {
        "id": "man-tgm-18290",
        "brand_id": "man",
        "brand_name": "MAN Truck & Bus",
        "model": "TGM 18.290 Distribution",
        "category": "Orta Tonaj Dağıtım Aracı",
        "plate": "34 MN 290",
        "source_address": 0x0C,  # J1939 SA: 12
        "engine": "D0836 6.9L 290 HP",
        "max_speed": 120.0,
        "default_speed": 65.0,
        "current_speed": 65.0,
        "target_speed": 65.0,
        "acceleration_rate": 2.9,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 5. DAF Trucks (SA: 0x0D, 0x0E, 0x0F)
    {
        "id": "daf-xg-plus-530",
        "brand_id": "daf",
        "brand_name": "DAF Trucks",
        "model": "XG+ 530 FT Next Gen",
        "category": "Geniş Kabin Uzun Yol",
        "plate": "34 DF 530",
        "source_address": 0x0D,  # J1939 SA: 13
        "engine": "PACCAR MX-13 12.9L 530 HP",
        "max_speed": 130.0,
        "default_speed": 86.0,
        "current_speed": 86.0,
        "target_speed": 86.0,
        "acceleration_rate": 2.6,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "daf-xf-480",
        "brand_id": "daf",
        "brand_name": "DAF Trucks",
        "model": "XF 480 FT Pure Excellence",
        "category": "Uluslararası Nakliye Çekicisi",
        "plate": "34 DF 480",
        "source_address": 0x0E,  # J1939 SA: 14
        "engine": "PACCAR MX-13 12.9L 480 HP",
        "max_speed": 125.0,
        "default_speed": 80.0,
        "current_speed": 80.0,
        "target_speed": 80.0,
        "acceleration_rate": 2.4,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "daf-cf-450",
        "brand_id": "daf",
        "brand_name": "DAF Trucks",
        "model": "CF 450 FAN Rigid",
        "category": "Çok Yönlü Belediye / Dağıtım",
        "plate": "34 DF 450",
        "source_address": 0x0F,  # J1939 SA: 15
        "engine": "PACCAR MX-11 10.8L 450 HP",
        "max_speed": 115.0,
        "default_speed": 58.0,
        "current_speed": 58.0,
        "target_speed": 58.0,
        "acceleration_rate": 2.7,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 6. Iveco (SA: 0x10, 0x11, 0x12)
    {
        "id": "iveco-s-way-570",
        "brand_id": "iveco",
        "brand_name": "Iveco",
        "model": "S-Way 570 Cursor 13",
        "category": "Yeni Nesil Uzun Yol Çekici",
        "plate": "34 IV 570",
        "source_address": 0x10,  # J1939 SA: 16
        "engine": "Cursor 13 12.9L 570 HP",
        "max_speed": 130.0,
        "default_speed": 84.0,
        "current_speed": 84.0,
        "target_speed": 84.0,
        "acceleration_rate": 2.6,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "iveco-eurocargo-160e",
        "brand_id": "iveco",
        "brand_name": "Iveco",
        "model": "Eurocargo 160E28 Tector",
        "category": "Orta Dağıtım ve Kargo Kamyonu",
        "plate": "34 IV 160",
        "source_address": 0x11,  # J1939 SA: 17
        "engine": "Tector 7 6.7L 280 HP",
        "max_speed": 120.0,
        "default_speed": 62.0,
        "current_speed": 62.0,
        "target_speed": 62.0,
        "acceleration_rate": 2.8,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "iveco-t-way-510",
        "brand_id": "iveco",
        "brand_name": "Iveco",
        "model": "T-Way 510 Heavy Off-Road",
        "category": "Ağır Maden & Taş Ocağı Aracı",
        "plate": "34 IV 510",
        "source_address": 0x12,  # J1939 SA: 18
        "engine": "Cursor 13 12.9L 510 HP",
        "max_speed": 105.0,
        "default_speed": 35.0,
        "current_speed": 35.0,
        "target_speed": 35.0,
        "acceleration_rate": 1.8,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 7. Ford Trucks (SA: 0x13, 0x14, 0x15)
    {
        "id": "ford-fmax-500",
        "brand_id": "ford_trucks",
        "brand_name": "Ford Trucks",
        "model": "F-MAX 500 Ecotorq",
        "category": "IToY Ödüllü Uzun Yol Çekicisi",
        "plate": "34 FT 500",
        "source_address": 0x13,  # J1939 SA: 19
        "engine": "Ecotorq 12.7L 500 HP",
        "max_speed": 130.0,
        "default_speed": 87.0,
        "current_speed": 87.0,
        "target_speed": 87.0,
        "acceleration_rate": 2.7,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "ford-cargo-1842t",
        "brand_id": "ford_trucks",
        "brand_name": "Ford Trucks",
        "model": "Cargo 1842T Tractor",
        "category": "Ağır Ticari Çekici",
        "plate": "34 FT 1842",
        "source_address": 0x14,  # J1939 SA: 20
        "engine": "Ecotorq 12.7L 420 HP",
        "max_speed": 125.0,
        "default_speed": 78.0,
        "current_speed": 78.0,
        "target_speed": 78.0,
        "acceleration_rate": 2.3,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "ford-fline-1833",
        "brand_id": "ford_trucks",
        "brand_name": "Ford Trucks",
        "model": "F-Line 1833 Yol Serisi",
        "category": "Yeni Nesil Yol & Dağıtım",
        "plate": "34 FT 1833",
        "source_address": 0x15,  # J1939 SA: 21
        "engine": "Ecotorq 9.0L 330 HP",
        "max_speed": 120.0,
        "default_speed": 64.0,
        "current_speed": 64.0,
        "target_speed": 64.0,
        "acceleration_rate": 2.8,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 8. Renault Trucks (SA: 0x16, 0x17, 0x18)
    {
        "id": "renault-t-high-520",
        "brand_id": "renault_trucks",
        "brand_name": "Renault Trucks",
        "model": "T-High 520 Sleeper Cab",
        "category": "Düz Taban Konforlu Uzun Yol",
        "plate": "34 RN 520",
        "source_address": 0x16,  # J1939 SA: 22
        "engine": "DE13 Turbo Compound 520 HP",
        "max_speed": 130.0,
        "default_speed": 85.0,
        "current_speed": 85.0,
        "target_speed": 85.0,
        "acceleration_rate": 2.6,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "renault-c-series-460",
        "brand_id": "renault_trucks",
        "brand_name": "Renault Trucks",
        "model": "C-Series 460 Construction",
        "category": "Şantiye & Zorlu Nakliye",
        "plate": "34 RN 460",
        "source_address": 0x17,  # J1939 SA: 23
        "engine": "DE11 10.8L 460 HP",
        "max_speed": 115.0,
        "default_speed": 52.0,
        "current_speed": 52.0,
        "target_speed": 52.0,
        "acceleration_rate": 2.2,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },
    {
        "id": "renault-k-series-480",
        "brand_id": "renault_trucks",
        "brand_name": "Renault Trucks",
        "model": "K-Series 480 Heavy Xtrem",
        "category": "Ağır Şantiye & Taş Ocağı",
        "plate": "34 RN 480",
        "source_address": 0x18,  # J1939 SA: 24
        "engine": "DE13 12.8L 480 HP",
        "max_speed": 105.0,
        "default_speed": 38.0,
        "current_speed": 38.0,
        "target_speed": 38.0,
        "acceleration_rate": 1.9,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 9. Isuzu (SA: 0x19, 0x1A, 0x1B)
    {
        "id": "isuzu-npr-10-long",
        "brand_id": "isuzu",
        "brand_name": "Isuzu",
        "model": "NPR 10 Long Şasi",
        "category": "Hafif Ticari & Şehir İçi Lojistik",
        "plate": "34 IS 010",
        "source_address": 0x19,  # J1939 SA: 25
        "engine": "4HK1-TCN 5.2L 190 HP",
        "max_speed": 120.0,
        "default_speed": 60.0,
        "current_speed": 60.0,
        "target_speed": 60.0,
        "acceleration_rate": 3.4,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "isuzu-giga-4x2",
        "brand_id": "isuzu",
        "brand_name": "Isuzu",
        "model": "Giga CXZ 460 Heavy Duty",
        "category": "Ağır Ticari Çekici",
        "plate": "34 IS 460",
        "source_address": 0x1A,  # J1939 SA: 26
        "engine": "6UZ1-TCC 9.8L 460 HP",
        "max_speed": 125.0,
        "default_speed": 77.0,
        "current_speed": 77.0,
        "target_speed": 77.0,
        "acceleration_rate": 2.4,
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "isuzu-forward-240",
        "brand_id": "isuzu",
        "brand_name": "Isuzu",
        "model": "Forward FVR 240 Kamyon",
        "category": "Orta Sınıf Kargo Taşımacılığı",
        "plate": "34 IS 240",
        "source_address": 0x1B,  # J1939 SA: 27
        "engine": "6HK1-TCS 7.8L 240 HP",
        "max_speed": 115.0,
        "default_speed": 55.0,
        "current_speed": 55.0,
        "target_speed": 55.0,
        "acceleration_rate": 2.7,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 10. BMC Otomotiv (SA: 0x1C, 0x1D, 0x1E)
    {
        "id": "bmc-tugra-1846",
        "brand_id": "bmc",
        "brand_name": "BMC Otomotiv",
        "model": "TUĞRA 1846 TGR Long Haul",
        "category": "Milli Uzun Yol Çekicisi",
        "plate": "34 BM 1846",
        "source_address": 0x1C,  # J1939 SA: 28
        "engine": "FPT Cursor 11 460 HP",
        "max_speed": 130.0,
        "default_speed": 84.0,
        "current_speed": 84.0,
        "target_speed": 84.0,
        "acceleration_rate": 2.5,
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "bmc-pro-1144",
        "brand_id": "bmc",
        "brand_name": "BMC Otomotiv",
        "model": "PRO 1144 8x4 Damperli",
        "category": "Ağır Şantiye ve Maden Kamyonu",
        "plate": "34 BM 1144",
        "source_address": 0x1D,  # J1939 SA: 29
        "engine": "Cummins ISL 8.9L 400 HP",
        "max_speed": 105.0,
        "default_speed": 42.0,
        "current_speed": 42.0,
        "target_speed": 42.0,
        "acceleration_rate": 2.0,
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },
    {
        "id": "bmc-neocity-85m",
        "brand_id": "bmc",
        "brand_name": "BMC Otomotiv",
        "model": "NEOCITY 8.5m VIP/Şehir İçi",
        "category": "Alçak Tabanlı Şehir İçi Otobüs",
        "plate": "34 BM 850",
        "source_address": 0x1E,  # J1939 SA: 30
        "engine": "Cummins ISB4.5 210 HP",
        "max_speed": 100.0,
        "default_speed": 35.0,
        "current_speed": 35.0,
        "target_speed": 35.0,
        "acceleration_rate": 2.8,
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
]


def get_all_vehicles() -> List[Dict[str, Any]]:
    """Tüm 30 aracın listesini döndürür"""
    return VEHICLES


def get_vehicle_by_id(vehicle_id: str) -> Dict[str, Any]:
    """ID'ye göre araç döndürür"""
    for v in VEHICLES:
        if v["id"] == vehicle_id:
            return v
    raise KeyError(f"Araç bulunamadı: {vehicle_id}")


def get_vehicles_by_brand(brand_id: str) -> List[Dict[str, Any]]:
    """Belirli bir markaya ait 3 modeli döndürür"""
    return [v for v in VEHICLES if v["brand_id"] == brand_id]
