"""
J1939 Passenger & Commercial Fleet Matrix: 10 Major Automotive Brands x 3 Iconic Models = 30 Vehicles
Includes Sedans, SUVs, Hatchbacks, Performance and Electric Vehicles.
Each vehicle contains unique SAE J1939 Source Address (SA: 0x01 to 0x1E), specs, telemetry status, and high-res web images.
"""

from typing import Dict, List, Any


FLEET_BRANDS = [
    {
        "id": "bmw",
        "name": "BMW",
        "country": "Germany",
        "color": "#0066B1",
        "badge": "BMW",
        "accent": "rgba(0, 102, 177, 0.2)",
    },
    {
        "id": "mercedes",
        "name": "Mercedes-Benz",
        "country": "Germany",
        "color": "#00D2FF",
        "badge": "MB",
        "accent": "rgba(0, 210, 255, 0.2)",
    },
    {
        "id": "audi",
        "name": "Audi",
        "country": "Germany",
        "color": "#F50537",
        "badge": "AUDI",
        "accent": "rgba(245, 5, 55, 0.2)",
    },
    {
        "id": "volkswagen",
        "name": "Volkswagen",
        "country": "Germany",
        "color": "#1E90FF",
        "badge": "VW",
        "accent": "rgba(30, 144, 255, 0.2)",
    },
    {
        "id": "toyota",
        "name": "Toyota",
        "country": "Japan",
        "color": "#EB0A1E",
        "badge": "TOYOTA",
        "accent": "rgba(235, 10, 30, 0.2)",
    },
    {
        "id": "tesla",
        "name": "Tesla",
        "country": "USA",
        "color": "#E82127",
        "badge": "TESLA",
        "accent": "rgba(232, 33, 39, 0.2)",
    },
    {
        "id": "ford",
        "name": "Ford",
        "country": "USA / Global",
        "color": "#118AB2",
        "badge": "FORD",
        "accent": "rgba(17, 138, 178, 0.2)",
    },
    {
        "id": "renault",
        "name": "Renault",
        "country": "France",
        "color": "#FFCC00",
        "badge": "RENAULT",
        "accent": "rgba(255, 204, 0, 0.2)",
    },
    {
        "id": "hyundai",
        "name": "Hyundai",
        "country": "South Korea",
        "color": "#002C6C",
        "badge": "HYUNDAI",
        "accent": "rgba(0, 44, 108, 0.2)",
    },
    {
        "id": "fiat",
        "name": "Fiat",
        "country": "Italy",
        "color": "#990000",
        "badge": "FIAT",
        "accent": "rgba(153, 0, 0, 0.2)",
    },
]


VEHICLES: List[Dict[str, Any]] = [
    # 1. BMW (SA: 0x01, 0x02, 0x03)
    {
        "id": "bmw-320i",
        "brand_id": "bmw",
        "brand_name": "BMW",
        "model": "320i Sedan M Sport",
        "category": "Premium Sedan",
        "plate": "34 BMW 320",
        "source_address": 0x01,
        "engine": "2.0L TwinPower Turbo 170 HP",
        "max_speed": 235.0,
        "default_speed": 110.0,
        "current_speed": 110.0,
        "target_speed": 110.0,
        "acceleration_rate": 6.5,
        "throttle_pct": 20.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 95.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "bmw-520d",
        "brand_id": "bmw",
        "brand_name": "BMW",
        "model": "520d Sedan xDrive",
        "category": "Executive Sedan",
        "plate": "34 BMW 520",
        "source_address": 0x02,
        "engine": "2.0L Mild-Hybrid Dizel 197 HP",
        "max_speed": 240.0,
        "default_speed": 120.0,
        "current_speed": 120.0,
        "target_speed": 120.0,
        "acceleration_rate": 6.8,
        "throttle_pct": 22.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 92.5,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "bmw-m4-competition",
        "brand_id": "bmw",
        "brand_name": "BMW",
        "model": "M4 Competition Coupe",
        "category": "Super Sport Coupe",
        "plate": "34 BMW 004",
        "source_address": 0x03,
        "engine": "3.0L M TwinPower Turbo 510 HP",
        "max_speed": 250.0,
        "default_speed": 140.0,
        "current_speed": 140.0,
        "target_speed": 140.0,
        "acceleration_rate": 12.0,
        "throttle_pct": 28.0,
        "brake_pct": 0.0,
        "gear": "D6",
        "battery_soc": 96.0,
        "battery_soh": 100.0,
        "image_url": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 2. Mercedes-Benz (SA: 0x04, 0x05, 0x06)
    {
        "id": "mb-c200",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "C200 4MATIC AMG",
        "category": "Premium Sedan",
        "plate": "34 MB 200",
        "source_address": 0x04,
        "engine": "1.5L Turbo EQ Boost 204 HP",
        "max_speed": 241.0,
        "default_speed": 115.0,
        "current_speed": 115.0,
        "target_speed": 115.0,
        "acceleration_rate": 6.7,
        "throttle_pct": 21.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 94.0,
        "battery_soh": 98.5,
        "image_url": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "mb-e300d",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "E300d 4MATIC Exclusive",
        "category": "Executive Luxury Sedan",
        "plate": "34 MB 300",
        "source_address": 0x05,
        "engine": "2.0L Turbo Dizel 265 HP",
        "max_speed": 250.0,
        "default_speed": 125.0,
        "current_speed": 125.0,
        "target_speed": 125.0,
        "acceleration_rate": 7.5,
        "throttle_pct": 24.0,
        "brake_pct": 0.0,
        "gear": "D6",
        "battery_soc": 91.0,
        "battery_soh": 97.5,
        "image_url": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "mb-g63-amg",
        "brand_id": "mercedes",
        "brand_name": "Mercedes-Benz",
        "model": "G63 AMG 4x4",
        "category": "Ultra Luxury Off-Road SUV",
        "plate": "34 MB 063",
        "source_address": 0x06,
        "engine": "4.0L V8 Biturbo 585 HP",
        "max_speed": 240.0,
        "default_speed": 100.0,
        "current_speed": 100.0,
        "target_speed": 100.0,
        "acceleration_rate": 10.5,
        "throttle_pct": 26.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 97.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 3. Audi (SA: 0x07, 0x08, 0x09)
    {
        "id": "audi-a3-sedan",
        "brand_id": "audi",
        "brand_name": "Audi",
        "model": "A3 Sedan 35 TFSI S line",
        "category": "Compact Luxury Sedan",
        "plate": "34 AU 350",
        "source_address": 0x07,
        "engine": "1.5L Turbo Mild-Hybrid 150 HP",
        "max_speed": 224.0,
        "default_speed": 90.0,
        "current_speed": 90.0,
        "target_speed": 90.0,
        "acceleration_rate": 5.8,
        "throttle_pct": 18.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 93.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "audi-a6-avant",
        "brand_id": "audi",
        "brand_name": "Audi",
        "model": "A6 Avant 40 TDI Quattro",
        "category": "Executive Station Wagon",
        "plate": "34 AU 460",
        "source_address": 0x08,
        "engine": "2.0L TDI Ultra 204 HP",
        "max_speed": 246.0,
        "default_speed": 120.0,
        "current_speed": 120.0,
        "target_speed": 120.0,
        "acceleration_rate": 7.0,
        "throttle_pct": 22.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 90.0,
        "battery_soh": 97.0,
        "image_url": "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "audi-rs6-avant",
        "brand_id": "audi",
        "brand_name": "Audi",
        "model": "RS6 Avant Performance",
        "category": "Super Sport Wagon",
        "plate": "34 AU 006",
        "source_address": 0x09,
        "engine": "4.0L V8 Biturbo TFSI 630 HP",
        "max_speed": 250.0,
        "default_speed": 150.0,
        "current_speed": 150.0,
        "target_speed": 150.0,
        "acceleration_rate": 13.5,
        "throttle_pct": 30.0,
        "brake_pct": 0.0,
        "gear": "D6",
        "battery_soc": 98.0,
        "battery_soh": 100.0,
        "image_url": "https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 4. Volkswagen (SA: 0x0A, 0x0B, 0x0C)
    {
        "id": "vw-golf-8",
        "brand_id": "volkswagen",
        "brand_name": "Volkswagen",
        "model": "Golf 8 1.5 eTSI R-Line",
        "category": "Hatchback",
        "plate": "34 VW 808",
        "source_address": 0x0A,
        "engine": "1.5L eTSI ACT 150 HP",
        "max_speed": 224.0,
        "default_speed": 85.0,
        "current_speed": 85.0,
        "target_speed": 85.0,
        "acceleration_rate": 5.9,
        "throttle_pct": 17.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 92.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "vw-passat-variant",
        "brand_id": "volkswagen",
        "brand_name": "Volkswagen",
        "model": "Passat Variant 2.0 TDI",
        "category": "Aile & Uzun Yol Station Wagon",
        "plate": "34 VW 200",
        "source_address": 0x0B,
        "engine": "2.0L TDI SCR 193 HP",
        "max_speed": 232.0,
        "default_speed": 115.0,
        "current_speed": 115.0,
        "target_speed": 115.0,
        "acceleration_rate": 6.4,
        "throttle_pct": 21.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 94.0,
        "battery_soh": 98.5,
        "image_url": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "vw-tiguan-rline",
        "brand_id": "volkswagen",
        "brand_name": "Volkswagen",
        "model": "Tiguan 1.5 eTSI R-Line",
        "category": "C-SUV",
        "plate": "34 VW 700",
        "source_address": 0x0C,
        "engine": "1.5L eTSI 150 HP",
        "max_speed": 210.0,
        "default_speed": 95.0,
        "current_speed": 95.0,
        "target_speed": 95.0,
        "acceleration_rate": 5.5,
        "throttle_pct": 19.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 93.5,
        "battery_soh": 97.5,
        "image_url": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },

    # 5. Toyota (SA: 0x0D, 0x0E, 0x0F)
    {
        "id": "toyota-corolla-hybrid",
        "brand_id": "toyota",
        "brand_name": "Toyota",
        "model": "Corolla 1.8 Hybrid Passion X-Pack",
        "category": "Sedan Hybrid",
        "plate": "34 TY 180",
        "source_address": 0x0D,
        "engine": "1.8L Kendi Kendini Şarj Eden Hibrit 140 HP",
        "max_speed": 180.0,
        "default_speed": 80.0,
        "current_speed": 80.0,
        "target_speed": 80.0,
        "acceleration_rate": 5.2,
        "throttle_pct": 16.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 78.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "toyota-rav4-hybrid",
        "brand_id": "toyota",
        "brand_name": "Toyota",
        "model": "RAV4 2.5 Hybrid AWD-i",
        "category": "D-SUV Hybrid",
        "plate": "34 TY 400",
        "source_address": 0x0E,
        "engine": "2.5L Dynamic Force Hybrid 222 HP",
        "max_speed": 190.0,
        "default_speed": 105.0,
        "current_speed": 105.0,
        "target_speed": 105.0,
        "acceleration_rate": 6.8,
        "throttle_pct": 20.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 82.0,
        "battery_soh": 98.5,
        "image_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "toyota-yaris-cross",
        "brand_id": "toyota",
        "brand_name": "Toyota",
        "model": "Yaris Cross 1.5 Hybrid",
        "category": "B-SUV Urban",
        "plate": "34 TY 150",
        "source_address": 0x0F,
        "engine": "1.5L Hybrid 116 HP",
        "max_speed": 170.0,
        "default_speed": 65.0,
        "current_speed": 65.0,
        "target_speed": 65.0,
        "acceleration_rate": 4.8,
        "throttle_pct": 15.0,
        "brake_pct": 0.0,
        "gear": "D3",
        "battery_soc": 85.0,
        "battery_soh": 99.5,
        "image_url": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },

    # 6. Tesla (SA: 0x10, 0x11, 0x12)
    {
        "id": "tesla-model-3-perf",
        "brand_id": "tesla",
        "brand_name": "Tesla",
        "model": "Model 3 Performance Dual Motor",
        "category": "Tam Elektrikli Sedan (EV)",
        "plate": "34 TS 003",
        "source_address": 0x10,
        "engine": "Dual Motor AWD Elektrik 510 HP",
        "max_speed": 250.0,
        "default_speed": 130.0,
        "current_speed": 130.0,
        "target_speed": 130.0,
        "acceleration_rate": 14.0,
        "throttle_pct": 25.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 88.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "tesla-model-y-longrange",
        "brand_id": "tesla",
        "brand_name": "Tesla",
        "model": "Model Y Long Range AWD",
        "category": "Tam Elektrikli SUV (EV)",
        "plate": "34 TS 009",
        "source_address": 0x11,
        "engine": "Dual Motor AWD Elektrik 384 HP",
        "max_speed": 217.0,
        "default_speed": 110.0,
        "current_speed": 110.0,
        "target_speed": 110.0,
        "acceleration_rate": 9.5,
        "throttle_pct": 20.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 84.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce3?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "tesla-model-s-plaid",
        "brand_id": "tesla",
        "brand_name": "Tesla",
        "model": "Model S Plaid Tri-Motor",
        "category": "Ultra Hyper EV Sedan",
        "plate": "34 TS 100",
        "source_address": 0x12,
        "engine": "Tri-Motor AWD Elektrik 1020 HP",
        "max_speed": 250.0,
        "default_speed": 160.0,
        "current_speed": 160.0,
        "target_speed": 160.0,
        "acceleration_rate": 18.0,
        "throttle_pct": 32.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 91.0,
        "battery_soh": 100.0,
        "image_url": "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },

    # 7. Ford (SA: 0x13, 0x14, 0x15)
    {
        "id": "ford-focus-st",
        "brand_id": "ford",
        "brand_name": "Ford",
        "model": "Focus ST 2.3 EcoBoost",
        "category": "Hot Hatchback",
        "plate": "34 FD 230",
        "source_address": 0x13,
        "engine": "2.3L EcoBoost 280 HP",
        "max_speed": 250.0,
        "default_speed": 120.0,
        "current_speed": 120.0,
        "target_speed": 120.0,
        "acceleration_rate": 8.2,
        "throttle_pct": 22.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 95.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1551522435-a13afa10f103?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "ford-mustang-gt",
        "brand_id": "ford",
        "brand_name": "Ford",
        "model": "Mustang GT 5.0 V8 Fastback",
        "category": "American Muscle Car",
        "plate": "34 FD 500",
        "source_address": 0x14,
        "engine": "5.0L Coyote V8 450 HP",
        "max_speed": 250.0,
        "default_speed": 135.0,
        "current_speed": 135.0,
        "target_speed": 135.0,
        "acceleration_rate": 11.0,
        "throttle_pct": 27.0,
        "brake_pct": 0.0,
        "gear": "D6",
        "battery_soc": 96.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "manual",
        "brake_pressed": False,
    },
    {
        "id": "ford-ranger-raptor",
        "brand_id": "ford",
        "brand_name": "Ford",
        "model": "Ranger Raptor 3.0 V6 Twin-Turbo",
        "category": "Performans Pick-up 4x4",
        "plate": "34 FD 900",
        "source_address": 0x15,
        "engine": "3.0L EcoBoost V6 292 HP",
        "max_speed": 180.0,
        "default_speed": 85.0,
        "current_speed": 85.0,
        "target_speed": 85.0,
        "acceleration_rate": 6.5,
        "throttle_pct": 18.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 93.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },

    # 8. Renault (SA: 0x16, 0x17, 0x18)
    {
        "id": "renault-clio-5",
        "brand_id": "renault",
        "brand_name": "Renault",
        "model": "Clio 5 1.0 TCe E-Tech",
        "category": "B Segment Hatchback",
        "plate": "34 RN 005",
        "source_address": 0x16,
        "engine": "1.0L Turbo Benzin 90 HP",
        "max_speed": 180.0,
        "default_speed": 70.0,
        "current_speed": 70.0,
        "target_speed": 70.0,
        "acceleration_rate": 4.6,
        "throttle_pct": 15.0,
        "brake_pct": 0.0,
        "gear": "D3",
        "battery_soc": 94.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "renault-megane-etech",
        "brand_id": "renault",
        "brand_name": "Renault",
        "model": "Megane E-Tech %100 Elektrikli",
        "category": "C-Crossover Elektrikli (EV)",
        "plate": "34 RN 220",
        "source_address": 0x17,
        "engine": "Elektrik Motoru EV60 220 HP",
        "max_speed": 160.0,
        "default_speed": 95.0,
        "current_speed": 95.0,
        "target_speed": 95.0,
        "acceleration_rate": 7.4,
        "throttle_pct": 19.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 86.0,
        "battery_soh": 98.5,
        "image_url": "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "renault-austral",
        "brand_id": "renault",
        "brand_name": "Renault",
        "model": "Austral 1.2 E-Tech Full Hybrid",
        "category": "C-SUV Hybrid",
        "plate": "34 RN 120",
        "source_address": 0x18,
        "engine": "1.2L E-Tech Full Hybrid 200 HP",
        "max_speed": 175.0,
        "default_speed": 90.0,
        "current_speed": 90.0,
        "target_speed": 90.0,
        "acceleration_rate": 6.2,
        "throttle_pct": 18.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 89.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },

    # 9. Hyundai (SA: 0x19, 0x1A, 0x1B)
    {
        "id": "hyundai-i20-n",
        "brand_id": "hyundai",
        "brand_name": "Hyundai",
        "model": "i20 N 1.6 T-GDI",
        "category": "Pocket Rocket Hot Hatch",
        "plate": "34 HY 020",
        "source_address": 0x19,
        "engine": "1.6L T-GDI Turbo 204 HP",
        "max_speed": 230.0,
        "default_speed": 115.0,
        "current_speed": 115.0,
        "target_speed": 115.0,
        "acceleration_rate": 8.0,
        "throttle_pct": 21.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 95.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "highway",
        "brake_pressed": False,
    },
    {
        "id": "hyundai-tucson-hybrid",
        "brand_id": "hyundai",
        "brand_name": "Hyundai",
        "model": "Tucson 1.6 T-GDI Hybrid 4x4",
        "category": "C-SUV",
        "plate": "34 HY 400",
        "source_address": 0x1A,
        "engine": "1.6L Hibrit AWD 230 HP",
        "max_speed": 193.0,
        "default_speed": 100.0,
        "current_speed": 100.0,
        "target_speed": 100.0,
        "acceleration_rate": 6.6,
        "throttle_pct": 20.0,
        "brake_pct": 0.0,
        "gear": "D5",
        "battery_soc": 84.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },
    {
        "id": "hyundai-ioniq-5",
        "brand_id": "hyundai",
        "brand_name": "Hyundai",
        "model": "Ioniq 5 Long Range AWD",
        "category": "Yeni Nesil Elektrikli Crossover",
        "plate": "34 HY 005",
        "source_address": 0x1B,
        "engine": "Çift Motor AWD Elektrik 325 HP",
        "max_speed": 185.0,
        "default_speed": 105.0,
        "current_speed": 105.0,
        "target_speed": 105.0,
        "acceleration_rate": 8.8,
        "throttle_pct": 19.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 87.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "cruise",
        "brake_pressed": False,
    },

    # 10. Fiat (SA: 0x1C, 0x1D, 0x1E)
    {
        "id": "fiat-egea-cross",
        "brand_id": "fiat",
        "brand_name": "Fiat",
        "model": "Egea Cross 1.5 Hibrit 130 HP",
        "category": "Crossover C Segment",
        "plate": "34 FT 150",
        "source_address": 0x1C,
        "engine": "1.5L FireFly Hibrit 130 HP",
        "max_speed": 200.0,
        "default_speed": 85.0,
        "current_speed": 85.0,
        "target_speed": 85.0,
        "acceleration_rate": 5.4,
        "throttle_pct": 17.0,
        "brake_pct": 0.0,
        "gear": "D4",
        "battery_soc": 90.0,
        "battery_soh": 98.0,
        "image_url": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "fiat-500e",
        "brand_id": "fiat",
        "brand_name": "Fiat",
        "model": "500e La Prima %100 Elektrikli",
        "category": "İkonik Şehir İçi EV",
        "plate": "34 FT 500",
        "source_address": 0x1D,
        "engine": "42 kWh Elektrik Motoru 118 HP",
        "max_speed": 150.0,
        "default_speed": 60.0,
        "current_speed": 60.0,
        "target_speed": 60.0,
        "acceleration_rate": 5.8,
        "throttle_pct": 14.0,
        "brake_pct": 0.0,
        "gear": "D",
        "battery_soc": 82.0,
        "battery_soh": 99.0,
        "image_url": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
    {
        "id": "fiat-doblo-combi",
        "brand_id": "fiat",
        "brand_name": "Fiat",
        "model": "Doblo Combi 1.5 BlueHDi",
        "category": "Hafif Ticari & Aile Aracı",
        "plate": "34 FT 155",
        "source_address": 0x1E,
        "engine": "1.5L BlueHDi Dizel 130 HP",
        "max_speed": 184.0,
        "default_speed": 75.0,
        "current_speed": 75.0,
        "target_speed": 75.0,
        "acceleration_rate": 5.1,
        "throttle_pct": 16.0,
        "brake_pct": 0.0,
        "gear": "D3",
        "battery_soc": 95.0,
        "battery_soh": 97.0,
        "image_url": "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?auto=format&fit=crop&w=800&q=80",
        "status": "cruising",
        "simulation_mode": "city",
        "brake_pressed": False,
    },
]


def get_all_vehicles() -> List[Dict[str, Any]]:
    """Tüm 30 binek ve ticari aracın listesini döndürür"""
    return VEHICLES


def get_vehicle_by_id(vehicle_id: str) -> Dict[str, Any]:
    """ID'ye göre araç döndürür"""
    for v in VEHICLES:
        if v["id"] == vehicle_id:
            return v
    raise KeyError(f"Araç bulunamadı: {vehicle_id}")


def get_vehicles_by_brand(brand_id: str) -> List[Dict[str, Any]]:
    """Belirli bir markaya ait 3 modeli döndürür"""
    return [v for v in VEHICLES if v["brand_id"] == brand_id]
